export const FOOD = [
  'Beef Salpicao',
  'Pinoy Chicken Curry',
  'Baked Macaroni',
  'Laswa',
  'Tortang Talong',
  'Ginisang Monggo',
  'Pinaputok na Tilapia',
  'Pork Menudo',
  'Pork Kaldereta',
  'Chicken Afritada',
  'Pork Steak',
  'Bicol Express',
  'Pata Tim',
  'Adobong Kangkong',
  'Pinakbet Tagalog',
  'Beef Stir Fry',
  'Pininyahang Manok',
  'Beef Asado',
  'Sweet and Sour Tilapia',
  'Ginataang Puso ng Saging',
  'Beef and Baby Corn Stir Fry',
  'Sinanglay na Tilapia',
  'Kung Pao Shrimp',
  'Chicken Lollipop',
  'Garlic Buttered Shrimp',
  'Sinigang na Hipon',
  'Chicken Mami',
  'Steamed Fish with Mayonnaise',
  'Bangus Sisig',
  'Fried Tilapia',
  'Pork and Chicken Adobo',
  'Paksiw na Pata',
  'Galbi',
  'Paklay',
  'Igado',
  'Vegetarian Pancit Canton',
  'Inihaw ng Bangus',
  'Tinolang Tahong',
  'Lechon Kawali',
  'Patotin',
  'Pancit Chami',
  'Sinarsahang Manok',
  'Pata Estofado',
  'Killer Pork Sinigang',
  'Pork Chao Fan',
  'Ketchup Fried Chicken',
  'Chicken Barbecue',
  'Java Rice with Pork Chop',
  'Tortang Talong',
  'Binagoongan Bagnet',
  'Pinangat na Galunggong sa Kamias',
  'Binagoongang Talong',
  'Pork Menudo',
  'Pork Caldereta',
  'Bicol Express Gising-gising',
  'Nilagang Baka',
  'Easy Utan Bisaya',
  'Chicken Paksiw',
  'Chicken Igado',
  'Crispy Kare-kare',
  'Halabos na Hipon with Butter',
  'Ginataang Kalabasa at Sitaw',
  'Sinigang Mix Inasal na Manok',
  'Pork Katsu Curry',
  'Crispy Pork Belly',
  'Chop Suey',
  'Chicken Binagoongan',
  'Sizzling Pusit',
  'Burger Steak',
  'Pineapple Chicken Afritada',
  'Pork Ribs Binagoongan',
  'Pork Menudo sa Gata',
  'Beef Stroganoff',
  'Fried Chicken',
  'Pata Potchero',
  'Pancit Batil Patung',
  'Lechon Paksiw',
  'Ginataang Alimasag',
  'Humba',
  'Sotanghon Chicken Soup',
  'Pata Kare-kare',
  'Pork Sisig',
  'Bangus Sisig',
  'Tokwa at Baboy',
  'Beef Papaitan',
  'Sweet and Sour Tilapia',
  'Sweet Pata Asado',
  'Spare Ribs Hamonado',
  'Ginataang Puso ng Saging',
  'Bulalo Kare-kare',
  'Crispy Liempo Sinigang',
  'Sinantomas',
  'Beef Mushroom',
  'Saucy Beef with Broccoli',
  'Spareribs Kaldereta',
  'Shrimp Laing',
  'Corned Beef Omelet',
  'Ginataang Tulingan',
];
